import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, IBM_Plex_Serif, Audiowide } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/NavBar";
import ModernChurchFooter from "@/components/footer";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});




const inter = Inter({ subsets: ["latin"], variable: '--font-inter' })
const ibmPlexSerif = Audiowide({
  subsets: ["latin"],
  weight: "400",
  variable: '--font-ibm-plex-serif'
})


export const metadata: Metadata = {
  title: "Overcomers INTL",
  description: "Generated by create next app",
  icons: {
    icon: "/overcomers.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${ibmPlexSerif.className}  antialiased scroll-smooth`}

      >
        <main className="w-full h-full" style={{
          boxSizing: "border-box"
        }}>
          <Navbar />
          {children}
          {/* <ModernChurchFooter /> */}
          <ScrollToTopButton />
        </main>

      </body>
    </html>
  );
}
